import Header from '@/app/components/header/Header'
import './globals.css'
import type { Metadata } from 'next'
import { Roboto } from 'next/font/google'
import Footer from '@/app/components/footer/Footer'


const roboto = Roboto({
  weight: ['400', '500', '700', '900'],
  style: ['normal'],
  subsets: ['latin'],
  display: 'swap',
})


export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="uk-UA">
      <body className={roboto.className}>
        <Header />
        <div className="container">
          
        <main>
          
            {children}
          
        </main>
          <Footer />
      </div>
        
      </body>
    </html>
  )
}
